### ISSUE TITLE
Node version doesn't build with latest Typescript versions

### ISSUE THREAD

**Issue by apulliam** [microsoft/BotBuilder-CognitiveServices#51]
I tried to build with Typescript version 2.5.2 and got these errors:

src/QnAMakerDialog.ts(39,14): error TS2415: Class 'QnAMakerDialog' incorrectly exte
nds base class 'Dialog'.
  Types of property 'dialogResumed' are incompatible.
    Type '(session: Session, result: IDialogResult<IQnAMakerResult>) => void' is no
t assignable to type '<T>(session: Session, result: IDialogResult<T>) => void'.
      Types of parameters 'result' and 'result' are incompatible.
        Type 'IDialogResult<T>' is not assignable to type 'IDialogResult<IQnAMakerR
esult>'.
          Type 'T' is not assignable to type 'IQnAMakerResult'.
src/QnAMakerTools.ts(64,57): error TS2559: Type 'IQnAMakerResult' has no properties
 in common with type 'IDialogResult<any>'.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
